### ISSUE TITLE
Chap

### ISSUE THREAD

**Issue by antoniovalenzuela** [mongramosjr/hotspot-login#1]
Hi,
chap support?

**Comment by mongramosjr** [comment]
This is a captive portal page for coova chilli. Please refer to the capability of coova chilli regarding authentication.

**Comment by mongramosjr** [comment]
anyway, athentication of wifi clients is performed by an external radius server. So you can setup chap in external radius such as freeradius

**Comment by antoniovalenzuela** [comment]
I mean the hotspotlogin.php file. 

In coovachilli I use chap, but the php file says pap or mschapv2 (which I do not use).

$ userpassword = "pap";

I see you have no integration with chap.

**Comment by mongramosjr** [comment]
Ok I got it, just leave it as empty in so that chilli_response will consider it as a CHAP response.
